param(
  [switch]$AutoGenerateDataset,
  [int]$WindowIndex = 1
)

$ErrorActionPreference = "Stop"

$repoRoot = $PSScriptRoot
while ($true) {
  $hasAFM04 = Test-Path -Path (Join-Path $repoRoot "AFM04")
  if ($hasAFM04) {
    break
  }

  $parent = Split-Path -Path $repoRoot -Parent
  if ([string]::IsNullOrEmpty($parent) -or $parent -eq $repoRoot) {
    throw "Could not locate repository root from $PSScriptRoot"
  }
  $repoRoot = $parent
}

Set-Location -Path $repoRoot

$pythonExe = Join-Path $repoRoot ".venv\Scripts\python.exe"
if (-not (Test-Path -Path $pythonExe)) {
  $pythonExe = "python"
}
$gboShardCount = if ($WindowIndex -gt 0) { 1 } else { 3 }

if ($AutoGenerateDataset.IsPresent) {
  $env:HNODECB_AFM04_MLP_TEST_AUTOGEN_DATASET = "1"
}

$env:HNODECB_AFM04_MLP_TEST_TRAIN_WINDOW_INDEX = "$WindowIndex"
$env:HNODECB_AFM04_MLP_TEST_SHARD_COUNT = "1"
$env:HNODECB_AFM04_MLP_TEST_WINDOW_MODE = "w0"
$env:HNODECB_AFM04_MLP_TEST_WINDOW_US = "6.288e-6"
$env:HNODECB_AFM04_MLP_TEST_WARMSTART_FROM_RANDOM_SEARCH = "1"
$env:HNODECB_AFM04_MLP_TEST_WARMSTART_FALLBACK_RANDOM = "1"

Write-Host "Running AFM04 MLP full functional test (MFT-GBO_only)"
Write-Host "Repo root  -> $repoRoot"
Write-Host "Python    -> $pythonExe"
Write-Host "Output dir -> AFM04\\MLP_full_test"
Write-Host "Mode       -> W0 only, MFT-GBO_only"
Write-Host "GBO shards -> 1"
Write-Host "Warmstart  -> RS best if present, else random init"

& $pythonExe -m AFM04.MLP_full_test.main --driver --warmstart-from-random-search --warmstart-fallback-random
$exitCode = $LASTEXITCODE

if ($exitCode -ne 0) {
  throw "AFM04 MLP full functional test (MFT-GBO_only) failed with exit code $exitCode"
}
