param(
  [int]$PrerunShards = 8,
  [int]$WindowIndex = 1,
  [string]$WindowTag = "w0",
  [int]$InputTopK = 100,
  [int]$LayerAEpochs = 10,
  [int]$LayerATopK = 20,
  [int]$LayerBEpochs = 20,
  [switch]$EnableAdaptiveGrid,
  [switch]$DisableAdaptiveGrid,
  [switch]$AutoGenerateDataset
)

$ErrorActionPreference = "Stop"

$repoRoot = $PSScriptRoot
while ($true) {
  $hasAFM04 = Test-Path -Path (Join-Path $repoRoot "AFM04")
  if ($hasAFM04) {
    break
  }

  $parent = Split-Path -Path $repoRoot -Parent
  if ([string]::IsNullOrEmpty($parent) -or $parent -eq $repoRoot) {
    throw "Could not locate repository root from $PSScriptRoot"
  }
  $repoRoot = $parent
}

Set-Location -Path $repoRoot

$pythonExe = Join-Path $repoRoot ".venv\Scripts\python.exe"
if (-not (Test-Path -Path $pythonExe)) {
  $pythonExe = "python"
}

$rsResultDir = Join-Path $repoRoot "AFM04\KAN_full_test\results\random_search"
$rsTrialsPath = Join-Path $rsResultDir "kan_full_test_random_search_trials_$WindowTag.json"
$rsSummaryPath = Join-Path $rsResultDir "kan_full_test_random_search_summary_$WindowTag.json"
$rsSeedsPath = Join-Path $rsResultDir "kan_full_test_random_search_trial_seeds.json"

if (-not (Test-Path -Path $rsTrialsPath)) {
  throw "Missing KFT RS trials file: $rsTrialsPath. Run run_KFT-RS_only_local.ps1 first."
}
if (-not (Test-Path -Path $rsSummaryPath)) {
  throw "Missing KFT RS summary file: $rsSummaryPath. Run run_KFT-RS_only_local.ps1 first."
}
if (-not (Test-Path -Path $rsSeedsPath)) {
  throw "Missing KFT RS seed bank file: $rsSeedsPath. Run run_KFT-RS_only_local.ps1 first."
}

$staleKftEnv = @(Get-ChildItem Env:HNODECB_AFM04_KAN_TEST_* -ErrorAction SilentlyContinue)
foreach ($item in $staleKftEnv) {
  Remove-Item -Path ("Env:\{0}" -f $item.Name) -ErrorAction SilentlyContinue
}

if ($AutoGenerateDataset.IsPresent) {
  $env:HNODECB_AFM04_KAN_TEST_AUTOGEN_DATASET = "1"
}

$env:HNODECB_AFM04_KAN_TEST_TRAIN_WINDOW_INDEX = "$WindowIndex"
$env:HNODECB_AFM04_KAN_TEST_RANDOM_SEARCH_WINDOW_INDEX = "$WindowIndex"
$env:HNODECB_AFM04_KAN_TEST_SHARD_COUNT = "1"
$env:HNODECB_AFM04_KAN_TEST_PRERUN_SHARD_COUNT = "$PrerunShards"
$env:HNODECB_AFM04_KAN_TEST_WINDOW_MODE = "w0"
$env:HNODECB_AFM04_KAN_TEST_WINDOW_US = "6.288e-6"
$env:HNODECB_AFM04_KAN_TEST_ADAPTIVE_GRID = if ($DisableAdaptiveGrid.IsPresent) { "0" } else { "1" }
$env:HNODECB_AFM04_KAN_TEST_WPRED = "0"
$env:HNODECB_AFM04_KAN_TEST_TRAIN_WPRED = "0"
$env:HNODECB_AFM04_KAN_TEST_WPRED_EPS = "1e-10"
$env:HNODECB_AFM04_KAN_TEST_SOFT_MASK = "1"
$env:HNODECB_AFM04_KAN_TEST_SOFT_MASK_TRAINABLE = "1"
$env:HNODECB_AFM04_KAN_TEST_SOFT_MASK_S0_A0 = "20"
$env:HNODECB_AFM04_KAN_TEST_SOFT_MASK_ALPHA_A0 = "0.25"
$env:HNODECB_AFM04_KAN_TEST_SOFT_MASK_S0_MIN_A0 = "1"
$env:HNODECB_AFM04_KAN_TEST_SOFT_MASK_S0_MAX_A0 = "100"
$env:HNODECB_AFM04_KAN_TEST_SOFT_MASK_ALPHA_MIN_A0 = "0.02"
$env:HNODECB_AFM04_KAN_TEST_SOFT_MASK_ALPHA_MAX_A0 = "5"
$env:HNODECB_AFM04_KAN_TEST_X3DOT_INPUT = "1"
$env:HNODECB_AFM04_KAN_TEST_X3DOT_INPUT_MODE = "t_level_lag"
$env:HNODECB_AFM04_KAN_TEST_X3DOT_INIT_POLICY = "minus_x2_init"
$env:HNODECB_AFM04_KAN_TEST_X3DOT_INIT_VALUE = "0"
$env:HNODECB_AFM04_KAN_TEST_X3DOT_INIT_TRAINABLE = "1"
$env:HNODECB_AFM04_KAN_TEST_X3DOT_SCALE_MODE = "x2_scale_tenth"
$env:HNODECB_AFM04_KAN_TEST_X3DOT_LAG_DETACH = "0"
$env:HNODECB_AFM04_KAN_TEST_PRERUN_INPUT_TOPK = "$InputTopK"
$env:HNODECB_AFM04_KAN_TEST_PRERUN_LAYER_A_EPOCHS = "$LayerAEpochs"
$env:HNODECB_AFM04_KAN_TEST_PRERUN_LAYER_A_TOPK = "$LayerATopK"
$env:HNODECB_AFM04_KAN_TEST_PRERUN_LAYER_B_EPOCHS = "$LayerBEpochs"
Remove-Item Env:\HNODECB_AFM04_KAN_TEST_WARMSTART_TRIAL -ErrorAction SilentlyContinue

Write-Host "Running AFM04 KAN prerun from existing RS results (KFT-prerun_from_RS)"
Write-Host "Repo root      -> $repoRoot"
Write-Host "Python         -> $pythonExe"
Write-Host "Output dir     -> AFM04\\KAN_full_test"
Write-Host "Mode           -> W0 only, existing RS required"
Write-Host "Hermetic env   -> cleared $($staleKftEnv.Count) stale KFT env vars"
Write-Host "AGU            -> $(if ($DisableAdaptiveGrid.IsPresent) { 'OFF' } else { 'ON' })"
Write-Host "Soft mask      -> ON (trainable in prerun; init s0=20*a0, alpha=0.25/a0, m_min=0)"
Write-Host "Plan Z         -> ON (4-9-1; T-level q lag attached; q fixed inside each [T_k,T_{k+1}]; q_init=-x2_init trainable)"
Write-Host "RS trials      -> $rsTrialsPath"
Write-Host "RS summary     -> $rsSummaryPath"
Write-Host "Prerun shards  -> $PrerunShards"
Write-Host "Layer A        -> RS top $InputTopK trials x $LayerAEpochs epochs"
Write-Host "Layer B        -> top $LayerATopK Layer-A winners, seamless resume x +$LayerBEpochs epochs"
Write-Host "Candidate root -> AFM04\\KAN_full_test\\candidate_runs\\prerun"

& $pythonExe -m AFM04.KAN_full_test.main --prerun-driver
$exitCode = $LASTEXITCODE

if ($exitCode -ne 0) {
  throw "AFM04 KAN prerun from existing RS results failed with exit code $exitCode"
}
