param(
  [switch]$AutoGenerateDataset,
  [switch]$EnableAdaptiveGrid,
  [switch]$DisableAdaptiveGrid,
  [int]$WindowIndex = 1,
  [int]$WarmstartTrial = 0,
  [int]$AdamEpochs = 20,
  [int]$TotalEpochs = 200,
  [int]$LBFGSEpochs = -1,
  [switch]$DisableLBFGS,
  [switch]$DisableStrongWolfe,
  [switch]$DisableHandoff,
  [switch]$ReplayHandoff,
  [string]$HandoffPath = "",
  [double]$LBFGSToleranceGrad = 1.0e-12,
  [double]$LBFGSToleranceChange = 1.0e-15,
  [ValidateSet("armijo_backtracking", "legacy_guard", "off")]
  [string]$StepController = "off"
)

$ErrorActionPreference = "Stop"

$repoRoot = $PSScriptRoot
while ($true) {
  $hasAFM04 = Test-Path -Path (Join-Path $repoRoot "AFM04")
  if ($hasAFM04) {
    break
  }

  $parent = Split-Path -Path $repoRoot -Parent
  if ([string]::IsNullOrEmpty($parent) -or $parent -eq $repoRoot) {
    throw "Could not locate repository root from $PSScriptRoot"
  }
  $repoRoot = $parent
}

Set-Location -Path $repoRoot

$pythonExe = Join-Path $repoRoot ".venv\Scripts\python.exe"
if (-not (Test-Path -Path $pythonExe)) {
  $pythonExe = "python"
}
$gboShardCount = if ($WindowIndex -gt 0) { 1 } else { 3 }
if ($AdamEpochs -lt 0) {
  throw "AdamEpochs must be >= 0"
}
$totalEpochsExplicit = $PSBoundParameters.ContainsKey("TotalEpochs")
if ($LBFGSEpochs -ge 0 -and -not $totalEpochsExplicit) {
  $TotalEpochs = $AdamEpochs + $LBFGSEpochs
}
if ($DisableLBFGS.IsPresent) {
  $TotalEpochs = $AdamEpochs
}
if ($TotalEpochs -lt 1) {
  throw "TotalEpochs must be >= 1"
}
if ($TotalEpochs -lt $AdamEpochs) {
  throw "TotalEpochs must be >= AdamEpochs"
}
$derivedLbfgsEpochs = $TotalEpochs - $AdamEpochs

$staleKftEnv = @(Get-ChildItem Env:HNODECB_AFM04_KAN_TEST_* -ErrorAction SilentlyContinue)
foreach ($item in $staleKftEnv) {
  Remove-Item -Path ("Env:\{0}" -f $item.Name) -ErrorAction SilentlyContinue
}

if ($AutoGenerateDataset.IsPresent) {
  $env:HNODECB_AFM04_KAN_TEST_AUTOGEN_DATASET = "1"
}

$env:HNODECB_AFM04_KAN_TEST_TRAIN_WINDOW_INDEX = "$WindowIndex"
$env:HNODECB_AFM04_KAN_TEST_SHARD_COUNT = "1"
$env:HNODECB_AFM04_KAN_TEST_WINDOW_MODE = "w0"
$env:HNODECB_AFM04_KAN_TEST_WINDOW_US = "6.288e-6"
$env:HNODECB_AFM04_KAN_TEST_EPOCHS = "$TotalEpochs"
$env:HNODECB_AFM04_KAN_TEST_ADAM_EPOCHS = "$AdamEpochs"
$env:HNODECB_AFM04_KAN_TEST_LR = "1e-5"
$env:HNODECB_AFM04_KAN_TEST_LBFGS_ENABLED = if ($DisableLBFGS.IsPresent -or $derivedLbfgsEpochs -le 0) { "0" } else { "1" }
$env:HNODECB_AFM04_KAN_TEST_LBFGS_STRONG_WOLFE = if ($DisableStrongWolfe.IsPresent) { "0" } else { "1" }
$env:HNODECB_AFM04_KAN_TEST_LBFGS_TOLERANCE_GRAD = "$LBFGSToleranceGrad"
$env:HNODECB_AFM04_KAN_TEST_LBFGS_TOLERANCE_CHANGE = "$LBFGSToleranceChange"
$env:HNODECB_AFM04_KAN_TEST_HANDOFF = if ($DisableHandoff.IsPresent) { "0" } else { "1" }
$env:HNODECB_AFM04_KAN_TEST_HANDOFF_REPLAY = if ($ReplayHandoff.IsPresent) { "1" } else { "0" }
if (-not [string]::IsNullOrWhiteSpace($HandoffPath)) {
  $env:HNODECB_AFM04_KAN_TEST_HANDOFF_PATH = "$HandoffPath"
}
$env:HNODECB_AFM04_KAN_TEST_ADAPTIVE_GRID = if ($DisableAdaptiveGrid.IsPresent) { "0" } else { "1" }
$env:HNODECB_AFM04_KAN_TEST_SOFT_MASK = "1"
$env:HNODECB_AFM04_KAN_TEST_SOFT_MASK_TRAINABLE = "1"
$env:HNODECB_AFM04_KAN_TEST_SOFT_MASK_S0_A0 = "20"
$env:HNODECB_AFM04_KAN_TEST_SOFT_MASK_ALPHA_A0 = "0.25"
$env:HNODECB_AFM04_KAN_TEST_SOFT_MASK_S0_MIN_A0 = "1"
$env:HNODECB_AFM04_KAN_TEST_SOFT_MASK_S0_MAX_A0 = "100"
$env:HNODECB_AFM04_KAN_TEST_SOFT_MASK_ALPHA_MIN_A0 = "0.02"
$env:HNODECB_AFM04_KAN_TEST_SOFT_MASK_ALPHA_MAX_A0 = "5"
$env:HNODECB_AFM04_KAN_TEST_X3DOT_INPUT = "1"
$env:HNODECB_AFM04_KAN_TEST_X3DOT_INPUT_MODE = "t_level_lag"
$env:HNODECB_AFM04_KAN_TEST_X3DOT_INIT_POLICY = "minus_x2_init"
$env:HNODECB_AFM04_KAN_TEST_X3DOT_INIT_VALUE = "0"
$env:HNODECB_AFM04_KAN_TEST_X3DOT_INIT_TRAINABLE = "1"
$env:HNODECB_AFM04_KAN_TEST_X3DOT_SCALE_MODE = "x2_scale_tenth"
$env:HNODECB_AFM04_KAN_TEST_X3DOT_LAG_DETACH = "1"
$env:HNODECB_AFM04_KAN_TEST_WARMSTART_FROM_PRERUN = "1"
$env:HNODECB_AFM04_KAN_TEST_PRERUN_WARMSTART_CANDIDATE = "1"
$env:HNODECB_AFM04_KAN_TEST_WARMSTART_FROM_RANDOM_SEARCH = "1"
$env:HNODECB_AFM04_KAN_TEST_WARMSTART_FALLBACK_RANDOM = "1"
$env:HNODECB_AFM04_KAN_TEST_STEP_CONTROLLER = "$StepController"
$env:HNODECB_AFM04_KAN_TEST_LR_ADAPT = "0"
$env:HNODECB_AFM04_KAN_TEST_PLATEAU_EARLY_STOP = "0"
$env:HNODECB_AFM04_KAN_TEST_RECENT_VAL_EARLY_STOP = "0"
if ($WarmstartTrial -gt 0) {
  $env:HNODECB_AFM04_KAN_TEST_WARMSTART_TRIAL = "$WarmstartTrial"
} else {
  Remove-Item Env:\HNODECB_AFM04_KAN_TEST_WARMSTART_TRIAL -ErrorAction SilentlyContinue
}

Write-Host "Running AFM04 KAN full functional test (KFT-GBO_only)"
Write-Host "Repo root  -> $repoRoot"
Write-Host "Python    -> $pythonExe"
Write-Host "Output dir -> AFM04\\KAN_full_test"
Write-Host "Mode       -> W0 only, KFT-GBO_only"
Write-Host "Hermetic env -> cleared $($staleKftEnv.Count) stale KFT env vars"
Write-Host "GBO shards -> 1"
Write-Host "Adam epochs  -> $AdamEpochs"
Write-Host "Adam lr      -> 1e-5"
Write-Host "LBFGS      -> $(if ($DisableLBFGS.IsPresent -or $derivedLbfgsEpochs -le 0) { 'OFF' } else { 'ON' })"
Write-Host "LBFGS epochs -> $derivedLbfgsEpochs (derived by Python as TotalEpochs - AdamEpochs)"
Write-Host "Total epochs -> $TotalEpochs"
Write-Host "Schedule   -> legacy total-minus-adam env path (LBFGS_EPOCHS/STEPS not set)"
Write-Host "LBFGS tol  -> grad=$LBFGSToleranceGrad change=$LBFGSToleranceChange"
Write-Host "Strong Wolfe -> $(if ($DisableStrongWolfe.IsPresent) { 'OFF' } else { 'ON' })"
Write-Host "Handoff   -> save $(if ($DisableHandoff.IsPresent) { 'OFF' } else { 'ON' }), replay $(if ($ReplayHandoff.IsPresent) { 'ON' } else { 'OFF' })"
if (-not [string]::IsNullOrWhiteSpace($HandoffPath)) {
  Write-Host "Handoff path -> $HandoffPath"
}
Write-Host "AGU        -> $(if ($DisableAdaptiveGrid.IsPresent) { 'OFF' } else { 'ON' })"
Write-Host "Soft mask  -> ON (trainable in GBO; init s0=20*a0, alpha=0.25/a0, m_min=0)"
Write-Host "Plan Z     -> ON (4-9-1; T-level q lag detached; q fixed inside each [T_k,T_{k+1}]; q_init=-x2_init trainable)"
Write-Host "Hidden norm -> refit once from selected warmstart rollout before GBO epoch 1"
Write-Host "Step ctrl  -> $StepController"
Write-Host "LR adapt   -> OFF"
Write-Host "Early stop -> OFF (plateau + recent-val)"
if ($ReplayHandoff.IsPresent) {
  Write-Host "Warmstart  -> handoff checkpoint replay; Adam loop skipped"
} elseif ($WarmstartTrial -gt 0) {
  Write-Host "Warmstart  -> RS trial $WarmstartTrial"
} else {
  Write-Host "Warmstart  -> prerun candidate 1 if present, else RS best, else deterministic random init"
}

& $pythonExe -m AFM04.KAN_full_test.main --driver --warmstart-from-random-search --warmstart-fallback-random
$exitCode = $LASTEXITCODE

if ($exitCode -ne 0) {
  throw "AFM04 KAN full functional test (KFT-GBO_only) failed with exit code $exitCode"
}
