param(
  [switch]$AutoGenerateDataset
)

$ErrorActionPreference = "Stop"

$repoRoot = $PSScriptRoot
while ($true) {
  $hasAFM04 = Test-Path -Path (Join-Path $repoRoot "AFM04")
  if ($hasAFM04) {
    break
  }

  $parent = Split-Path -Path $repoRoot -Parent
  if ([string]::IsNullOrEmpty($parent) -or $parent -eq $repoRoot) {
    throw "Could not locate repository root from $PSScriptRoot"
  }
  $repoRoot = $parent
}

Set-Location -Path $repoRoot

if ($AutoGenerateDataset.IsPresent) {
  $env:HNODECB_AFM04_KAN_TEST_AUTOGEN_DATASET = "1"
}

$env:HNODECB_AFM04_KAN_TEST_WARMSTART_FROM_RANDOM_SEARCH = "1"
$env:HNODECB_AFM04_KAN_TEST_WARMSTART_FALLBACK_RANDOM = "1"

Write-Host "Running AFM04 KAN full functional test (KFT-GBO_only)"
Write-Host "Repo root  -> $repoRoot"
Write-Host "Output dir -> AFM04\\KAN_full_test"
Write-Host "Mode       -> 3 shards (W1/W2/W3), KFT-GBO_only"
Write-Host "Warmstart  -> RS best if present, else random init"

python -m AFM04.KAN_full_test.main --driver --warmstart-from-random-search --warmstart-fallback-random
$exitCode = $LASTEXITCODE

if ($exitCode -ne 0) {
  throw "AFM04 KAN full functional test (KFT-GBO_only) failed with exit code $exitCode"
}
