param(
  [switch]$AutoGenerateDataset,
  [int]$Trials = 1000,
  [int]$WindowIndex = 1
)

$ErrorActionPreference = "Stop"

$repoRoot = $PSScriptRoot
while ($true) {
  $hasAFM04 = Test-Path -Path (Join-Path $repoRoot "AFM04")
  if ($hasAFM04) {
    break
  }

  $parent = Split-Path -Path $repoRoot -Parent
  if ([string]::IsNullOrEmpty($parent) -or $parent -eq $repoRoot) {
    throw "Could not locate repository root from $PSScriptRoot"
  }
  $repoRoot = $parent
}

Set-Location -Path $repoRoot

if ($AutoGenerateDataset.IsPresent) {
  $env:HNODECB_AFM04_KAN_TEST_AUTOGEN_DATASET = "1"
}
$env:HNODECB_AFM04_KAN_TEST_RANDOM_SEARCH_TRIALS = "$Trials"
$env:HNODECB_AFM04_KAN_TEST_RANDOM_SEARCH_TRUE_RANDOM = "0"
$env:HNODECB_AFM04_KAN_TEST_RANDOM_SEARCH_USE_VAL = "0"
$env:HNODECB_AFM04_KAN_TEST_RANDOM_SEARCH_SUBSHARD_COUNT = "5"
$env:HNODECB_AFM04_KAN_TEST_RANDOM_SEARCH_FAIL_FAST = "1"
$env:HNODECB_AFM04_KAN_TEST_RANDOM_SEARCH_X1_GUARD_MULT = "100"
$env:HNODECB_AFM04_KAN_TEST_RANDOM_SEARCH_X2_GUARD_MULT = "100"
$env:HNODECB_AFM04_KAN_TEST_RANDOM_SEARCH_WINDOW_INDEX = "$WindowIndex"
$env:HNODECB_AFM04_KAN_TEST_TRAIN_WINDOW_INDEX = "0"
$env:HNODECB_AFM04_KAN_TEST_SHARD_COUNT = "3"
$env:HNODECB_AFM04_KAN_TEST_WPRED = "0"
$env:HNODECB_AFM04_KAN_TEST_TRAIN_WPRED = "0"
$env:HNODECB_AFM04_KAN_TEST_WPRED_EPS = "1e-10"
$env:HNODECB_AFM04_KAN_TEST_RETRY_LR_FACTOR = "0.3"
$env:HNODECB_AFM04_KAN_TEST_STEP_RETRY_LR_FACTOR = "0.3"
$env:HNODECB_AFM04_KAN_TEST_RECENT_VAL_WINDOW = "30"

Write-Host "Running AFM04 KAN full functional test"
Write-Host "Repo root  -> $repoRoot"
Write-Host "Output dir -> AFM04\\KAN_full_test"
if ($WindowIndex -gt 0) {
  Write-Host "GS Mode    -> W$WindowIndex only"
  Write-Host "GBO Mode   -> W1/W2/W3"
} else {
  Write-Host "Mode       -> W1/W2/W3 for GS + GBO"
}
Write-Host "GS shards  -> 5 compute shards total"
Write-Host "Pre-stage  -> random search before gradient optimization"
Write-Host "GS metric  -> train-only (val eval OFF)"
Write-Host "GS seeds   -> deterministic pseudo-random"
Write-Host "GS guard   -> ON"
Write-Host "GS w_pred  -> OFF"
Write-Host "GBO w_pred -> OFF"
Write-Host "Trials     -> $Trials"

python -m AFM04.KAN_full_test.main --driver --with-random-search
$exitCode = $LASTEXITCODE

if ($exitCode -ne 0) {
  throw "AFM04 KAN full functional test with random search failed with exit code $exitCode"
}
