param(
  [switch]$AutoGenerateDataset,
  [switch]$EnableAdaptiveGrid,
  [switch]$DisableAdaptiveGrid,
  [int]$Trials = 500,
  [int]$SeedBase = 860197144,
  [int]$WindowIndex = 1
)

$ErrorActionPreference = "Stop"

$repoRoot = $PSScriptRoot
while ($true) {
  $hasAFM04 = Test-Path -Path (Join-Path $repoRoot "AFM04")
  if ($hasAFM04) {
    break
  }

  $parent = Split-Path -Path $repoRoot -Parent
  if ([string]::IsNullOrEmpty($parent) -or $parent -eq $repoRoot) {
    throw "Could not locate repository root from $PSScriptRoot"
  }
  $repoRoot = $parent
}

Set-Location -Path $repoRoot

$pythonExe = Join-Path $repoRoot ".venv\Scripts\python.exe"
if (-not (Test-Path -Path $pythonExe)) {
  $pythonExe = "python"
}

$staleKftEnv = @(Get-ChildItem Env:HNODECB_AFM04_KAN_TEST_* -ErrorAction SilentlyContinue)
foreach ($item in $staleKftEnv) {
  Remove-Item -Path ("Env:\{0}" -f $item.Name) -ErrorAction SilentlyContinue
}

if ($AutoGenerateDataset.IsPresent) {
  $env:HNODECB_AFM04_KAN_TEST_AUTOGEN_DATASET = "1"
}

$env:HNODECB_AFM04_KAN_TEST_RANDOM_SEARCH_TRIALS = "$Trials"
$env:HNODECB_AFM04_KAN_TEST_SEED = "$SeedBase"
$env:HNODECB_AFM04_KAN_TEST_RANDOM_SEARCH_TRUE_RANDOM = "0"
$env:HNODECB_AFM04_KAN_TEST_RANDOM_SEARCH_USE_VAL = "0"
$env:HNODECB_AFM04_KAN_TEST_RANDOM_SEARCH_SUBSHARD_COUNT = "8"
$env:HNODECB_AFM04_KAN_TEST_RANDOM_SEARCH_FAIL_FAST = "1"
$env:HNODECB_AFM04_KAN_TEST_RANDOM_SEARCH_X1_GUARD_MULT = "5"
$env:HNODECB_AFM04_KAN_TEST_RANDOM_SEARCH_X2_GUARD_MULT = "5"
$env:HNODECB_AFM04_KAN_TEST_RANDOM_SEARCH_WINDOW_INDEX = "$WindowIndex"
$env:HNODECB_AFM04_KAN_TEST_TRAIN_WINDOW_INDEX = "$WindowIndex"
$env:HNODECB_AFM04_KAN_TEST_SHARD_COUNT = "1"
$env:HNODECB_AFM04_KAN_TEST_WINDOW_MODE = "w0"
$env:HNODECB_AFM04_KAN_TEST_WINDOW_US = "6.288e-6"
$env:HNODECB_AFM04_KAN_TEST_ADAPTIVE_GRID = if ($DisableAdaptiveGrid.IsPresent) { "0" } else { "1" }
$env:HNODECB_AFM04_KAN_TEST_WPRED = "0"
$env:HNODECB_AFM04_KAN_TEST_TRAIN_WPRED = "0"
$env:HNODECB_AFM04_KAN_TEST_WPRED_EPS = "1e-10"
$env:HNODECB_AFM04_KAN_TEST_SOFT_MASK = "1"
$env:HNODECB_AFM04_KAN_TEST_SOFT_MASK_TRAINABLE = "0"
$env:HNODECB_AFM04_KAN_TEST_SOFT_MASK_S0_A0 = "20"
$env:HNODECB_AFM04_KAN_TEST_SOFT_MASK_ALPHA_A0 = "0.25"
$env:HNODECB_AFM04_KAN_TEST_SOFT_MASK_S0_MIN_A0 = "1"
$env:HNODECB_AFM04_KAN_TEST_SOFT_MASK_S0_MAX_A0 = "100"
$env:HNODECB_AFM04_KAN_TEST_SOFT_MASK_ALPHA_MIN_A0 = "0.02"
$env:HNODECB_AFM04_KAN_TEST_SOFT_MASK_ALPHA_MAX_A0 = "5"
$env:HNODECB_AFM04_KAN_TEST_X3DOT_INPUT = "1"
$env:HNODECB_AFM04_KAN_TEST_X3DOT_INPUT_MODE = "t_level_lag"
$env:HNODECB_AFM04_KAN_TEST_X3DOT_INIT_POLICY = "minus_x2_init"
$env:HNODECB_AFM04_KAN_TEST_X3DOT_INIT_VALUE = "0"
$env:HNODECB_AFM04_KAN_TEST_X3DOT_INIT_TRAINABLE = "0"
$env:HNODECB_AFM04_KAN_TEST_X3DOT_SCALE_MODE = "x2_scale_tenth"
$env:HNODECB_AFM04_KAN_TEST_X3DOT_LAG_DETACH = "0"
Remove-Item Env:\HNODECB_AFM04_KAN_TEST_WARMSTART_TRIAL -ErrorAction SilentlyContinue

Write-Host "Running AFM04 KAN random search only (KFT-RS_only)"
Write-Host "Repo root  -> $repoRoot"
Write-Host "Python    -> $pythonExe"
Write-Host "Output dir -> AFM04\\KAN_full_test"
Write-Host "Mode       -> W0 only, KFT-RS_only"
Write-Host "Hermetic env -> cleared $($staleKftEnv.Count) stale KFT env vars"
Write-Host "RS shards  -> 8 compute shards total"
Write-Host "RS metric  -> train-only (val eval OFF)"
Write-Host "RS seeds   -> rerolled deterministic pseudo-random (base seed $SeedBase)"
Write-Host "RS guard   -> ON"
Write-Host "RS w_pred  -> OFF"
Write-Host "Soft mask  -> ON (fixed in RS; s0=20*a0, alpha=0.25/a0, m_min=0)"
Write-Host "Plan Z     -> ON (4-9-1; T-level q lag attached; q fixed inside each [T_k,T_{k+1}]; q_init=-x2_init fixed in RS)"
Write-Host "AGU        -> $(if ($DisableAdaptiveGrid.IsPresent) { 'OFF' } else { 'ON' })"
Write-Host "Trials     -> $Trials"

& $pythonExe -m AFM04.KAN_full_test.main --random-search-driver
$exitCode = $LASTEXITCODE

if ($exitCode -ne 0) {
  throw "AFM04 KAN random search only (KFT-RS_only) failed with exit code $exitCode"
}
