param(
  [int]$Shards = 6,
  [switch]$AutoGenerateDataset,
  [switch]$StopAfterLayerA
)

$ErrorActionPreference = "Stop"

$repoRoot = $PSScriptRoot
while ($true) {
  $hasAFM05 = Test-Path -Path (Join-Path $repoRoot "AFM05")
  if ($hasAFM05) {
    break
  }

  $parent = Split-Path -Path $repoRoot -Parent
  if ([string]::IsNullOrEmpty($parent) -or $parent -eq $repoRoot) {
    throw "Could not locate repository root from $PSScriptRoot"
  }
  $repoRoot = $parent
}

Set-Location -Path $repoRoot

$pythonExe = Join-Path $repoRoot ".venv\Scripts\python.exe"
if (-not (Test-Path -Path $pythonExe)) {
  $pythonExe = "python"
}

$schedulePath = Join-Path $repoRoot "AFM05\stage2light\stage2light_schedule.json"
$schedule = Get-Content -LiteralPath $schedulePath -Raw | ConvertFrom-Json
$stage2Epochs = [int]$schedule.epochs
$stage2AdamEpochs = [int]$schedule.adam_epochs
$stage2LbfgsEpochs = [int]$schedule.lbfgs_epochs
if ($stage2AdamEpochs -gt $stage2Epochs) {
  $stage2AdamEpochs = $stage2Epochs
}
if (($stage2AdamEpochs + $stage2LbfgsEpochs) -ne $stage2Epochs) {
  $stage2LbfgsEpochs = [Math]::Max(0, $stage2Epochs - $stage2AdamEpochs)
}

$stage1InputPath = Join-Path $repoRoot "AFM05\stage1pluslight\results_afm\afm_param_stage1pluslight_05.pkl"

$stalePrest2Env = @(
  Get-ChildItem Env:HNODECB_AFM05_PREST2_* -ErrorAction SilentlyContinue
  Get-ChildItem Env:HNODECB_AFM05_STAGE2LIGHT_* -ErrorAction SilentlyContinue
)
foreach ($item in $stalePrest2Env) {
  Remove-Item -Path ("Env:\{0}" -f $item.Name) -ErrorAction SilentlyContinue
}

$env:HNODECB_AFM05_PREST2_INPUT_PATH = $stage1InputPath
$env:HNODECB_AFM05_PREST2_SHARD_COUNT = "$Shards"
$env:HNODECB_AFM05_PREST2_LAYER_A_TOP_CANDIDATES = "30"
$env:HNODECB_AFM05_PREST2_LAYER_A_ZONE_FILTER = "all"
$env:HNODECB_AFM05_PREST2_LAYER_A_EPOCHS = "20"
$env:HNODECB_AFM05_PREST2_LAYER_B_TOP_CANDIDATES = "10"
$env:HNODECB_AFM05_PREST2_LAYER_B_EPOCHS = "20"
$env:HNODECB_AFM05_PREST2_STOP_AFTER_LAYER_A = if ($StopAfterLayerA.IsPresent) { "1" } else { "0" }
$env:HNODECB_AFM05_PREST2_CHECKPOINT_EVERY = "1"
$env:HNODECB_AFM05_PREST2_AUTOGEN_DATASET = if ($AutoGenerateDataset.IsPresent) { "1" } else { "0" }
$env:HNODECB_AFM05_PREST2_CANDIDATE_METRIC = "final_train_loss"
$env:HNODECB_AFM05_PREST2_STAGE2_ADAM_EPOCHS = "$stage2AdamEpochs"
$env:HNODECB_AFM05_STAGE2LIGHT_WINDOW_MODE = "window_05_initial"
$env:HNODECB_AFM05_STAGE2LIGHT_PIXEL_TAG = "184_152"
$env:HNODECB_AFM05_STAGE2LIGHT_WINDOW_US = "25.152e-6"
$env:HNODECB_AFM05_STAGE2LIGHT_WINDOW_SAMPLE_STRIDE = "16"
$env:HNODECB_AFM05_STAGE2LIGHT_VAL_STRIDE = "5"
$env:HNODECB_AFM05_STAGE2LIGHT_VAL_OFFSET = "2"
$env:HNODECB_AFM05_STAGE2LIGHT_NOISE_SCALE = "0.1"

$driverLogHint = Join-Path $repoRoot "AFM05\prestage2\logs"

Write-Host "Running AFM05 prestage2 with SHARDS=$Shards"
Write-Host "Layer A -> lowest 30 st1pl best-seed envelope points across all zones, 20 epochs (10 Adam + 10 L-BFGS)"
Write-Host "Layer B -> top 10 of Layer A, seamless resume for 20 more epochs to epoch 40 (20 L-BFGS)"
Write-Host "Stop after Layer A -> $($StopAfterLayerA.IsPresent)"
Write-Host "Main schedule -> st2l total=$stage2Epochs, Adam prefix=$stage2AdamEpochs, LBFGS suffix=$stage2LbfgsEpochs"
Write-Host "Prest2 rule -> layers choose candidate set and prefix length only; optimizer phases are copied from st2l epoch numbers"
Write-Host "Metric  -> final_train_loss"
Write-Host "KAN noise_scale -> $env:HNODECB_AFM05_STAGE2LIGHT_NOISE_SCALE"
Write-Host "Window -> window_05_initial, span 25.152e-6 s, sample stride 16, split 4:1"
Write-Host "Hermetic env -> cleared $($stalePrest2Env.Count) stale prest2/stage2 vars"
Write-Host "Stage1 input -> $stage1InputPath"
Write-Host "Repo root -> $repoRoot"
Write-Host "Python    -> $pythonExe"
Write-Host "Logs dir  -> $driverLogHint"

& $pythonExe -m AFM05.prestage2.main --driver
$exitCode = $LASTEXITCODE

if ($exitCode -ne 0) {
  throw "AFM05 prestage2 local run failed with exit code $exitCode. See logs under $driverLogHint"
}
