param(
  [int]$Shards = 1,
  [switch]$AutoGenerateDataset
)

$ErrorActionPreference = "Stop"

$repoRoot = $PSScriptRoot
while ($true) {
  $hasAFM04 = Test-Path -Path (Join-Path $repoRoot "AFM04")
  if ($hasAFM04) {
    break
  }

  $parent = Split-Path -Path $repoRoot -Parent
  if ([string]::IsNullOrEmpty($parent) -or $parent -eq $repoRoot) {
    throw "Could not locate repository root from $PSScriptRoot"
  }
  $repoRoot = $parent
}

Set-Location -Path $repoRoot

$pythonExe = Join-Path $repoRoot ".venv\Scripts\python.exe"
if (-not (Test-Path -Path $pythonExe)) {
  $pythonExe = "python"
}

$schedulePath = Join-Path $repoRoot "AFM04\stage2light\stage2light_schedule.json"
$schedule = Get-Content -LiteralPath $schedulePath -Raw | ConvertFrom-Json
$stage2Epochs = [int]$schedule.epochs
$stage2AdamEpochs = [int]$schedule.adam_epochs
$stage2LbfgsEpochs = [int]$schedule.lbfgs_epochs
if ($stage2AdamEpochs -gt $stage2Epochs) {
  $stage2AdamEpochs = $stage2Epochs
}
if (($stage2AdamEpochs + $stage2LbfgsEpochs) -ne $stage2Epochs) {
  $stage2LbfgsEpochs = [Math]::Max(0, $stage2Epochs - $stage2AdamEpochs)
}

$staleStage2Env = @(Get-ChildItem Env:HNODECB_AFM04_STAGE2LIGHT_* -ErrorAction SilentlyContinue)
foreach ($item in $staleStage2Env) {
  Remove-Item -Path ("Env:\{0}" -f $item.Name) -ErrorAction SilentlyContinue
}

$env:HNODECB_AFM04_STAGE2LIGHT_SHARD_COUNT = "$Shards"
$env:HNODECB_AFM04_STAGE2LIGHT_AUTOGEN_DATASET = if ($AutoGenerateDataset.IsPresent) { "1" } else { "0" }
$env:HNODECB_AFM04_STAGE2LIGHT_WINDOW_MODE = "w0"
$env:HNODECB_AFM04_STAGE2LIGHT_WINDOW_US = "6.288e-6"
Remove-Item Env:\HNODECB_AFM04_STAGE2LIGHT_INPUT_RANK -ErrorAction SilentlyContinue
Remove-Item Env:\HNODECB_AFM04_STAGE2LIGHT_INPUT_TRIAL_ID -ErrorAction SilentlyContinue
Remove-Item Env:\HNODECB_AFM04_STAGE2LIGHT_INPUT_MECH_WINNER -ErrorAction SilentlyContinue
$env:HNODECB_AFM04_STAGE2LIGHT_WARMSTART_SOURCE = "prest2"
$env:HNODECB_AFM04_STAGE2LIGHT_INPUT_CANDIDATE = "11"
$env:HNODECB_AFM04_STAGE2LIGHT_PREST2_INPUT_PATH = Join-Path $repoRoot "AFM04\prestage2\results\afm_prest2_04_candidates_b.pkl"
$env:HNODECB_AFM04_STAGE2LIGHT_RESUME = "1"
$env:HNODECB_AFM04_STAGE2LIGHT_EPOCHS = "$stage2Epochs"
$env:HNODECB_AFM04_STAGE2LIGHT_ADAM_EPOCHS = "$stage2AdamEpochs"
$env:HNODECB_AFM04_STAGE2LIGHT_LBFGS_EPOCHS = "$stage2LbfgsEpochs"
$env:HNODECB_AFM04_STAGE2LIGHT_SOFT_MASK = "1"
$env:HNODECB_AFM04_STAGE2LIGHT_SOFT_MASK_TRAINABLE = "1"
$env:HNODECB_AFM04_STAGE2LIGHT_SOFT_MASK_S0_A0 = "20.0"
$env:HNODECB_AFM04_STAGE2LIGHT_SOFT_MASK_S0_MIN_A0 = "1.0"
$env:HNODECB_AFM04_STAGE2LIGHT_SOFT_MASK_S0_MAX_A0 = "100.0"
$env:HNODECB_AFM04_STAGE2LIGHT_SOFT_MASK_ALPHA_A0 = "0.25"
$env:HNODECB_AFM04_STAGE2LIGHT_SOFT_MASK_ALPHA_MIN_A0 = "0.02"
$env:HNODECB_AFM04_STAGE2LIGHT_SOFT_MASK_ALPHA_MAX_A0 = "5.0"
$env:HNODECB_AFM04_STAGE2LIGHT_LR = "1e-3"
$env:HNODECB_AFM04_STAGE2LIGHT_LR_ADAPT = "0"
$env:HNODECB_AFM04_STAGE2LIGHT_LR_ADAPT_UP_ONLY = "0"
$env:HNODECB_AFM04_STAGE2LIGHT_MECH_PARAMETERIZATION = "log_relative"
$env:HNODECB_AFM04_STAGE2LIGHT_LR_MIN = "1e-6"
$env:HNODECB_AFM04_STAGE2LIGHT_LR_MAX = "1e-2"
$env:HNODECB_AFM04_STAGE2LIGHT_LR_ETA = "0.05"
$env:HNODECB_AFM04_STAGE2LIGHT_LR_EMA = "0.97"
$env:HNODECB_AFM04_STAGE2LIGHT_EPOCH_RETRIES = "0"
$env:HNODECB_AFM04_STAGE2LIGHT_RETRY_LR_FACTOR = "0.3"
$env:HNODECB_AFM04_STAGE2LIGHT_RETRY_LR_FLOOR = "1e-6"
$env:HNODECB_AFM04_STAGE2LIGHT_STEP_CONTROLLER = "off"
$env:HNODECB_AFM04_STAGE2LIGHT_STEP_GUARD = "0"
$env:HNODECB_AFM04_STAGE2LIGHT_STEP_RETRIES = "0"
$env:HNODECB_AFM04_STAGE2LIGHT_STEP_RETRY_LR_FACTOR = "0.3"
$env:HNODECB_AFM04_STAGE2LIGHT_STEP_RETRY_RESET_LR_EACH_EPOCH = "0"
$env:HNODECB_AFM04_STAGE2LIGHT_STEP_GUARD_VALIDATE_VAL = "0"
$env:HNODECB_AFM04_STAGE2LIGHT_STEP_MAX_LOSS_INCREASE_FRAC = "0.05"
$env:HNODECB_AFM04_STAGE2LIGHT_ARMIJO_C1 = "1e-4"
$env:HNODECB_AFM04_STAGE2LIGHT_BACKTRACK_SHRINK = "0.5"
$env:HNODECB_AFM04_STAGE2LIGHT_BACKTRACK_MAX = "10"
$env:HNODECB_AFM04_STAGE2LIGHT_BACKTRACK_MIN_ALPHA = "1e-8"
$env:HNODECB_AFM04_STAGE2LIGHT_LBFGS_ENABLED = if ($stage2LbfgsEpochs -gt 0) { "1" } else { "0" }
$env:HNODECB_AFM04_STAGE2LIGHT_LBFGS_STRONG_WOLFE = "1"
$env:HNODECB_AFM04_STAGE2LIGHT_LBFGS_LR = "1.0"
$env:HNODECB_AFM04_STAGE2LIGHT_LBFGS_MAX_ITER = "1"
$env:HNODECB_AFM04_STAGE2LIGHT_LBFGS_MAX_EVAL = "10"
$env:HNODECB_AFM04_STAGE2LIGHT_LBFGS_HISTORY_SIZE = "100"
$env:HNODECB_AFM04_STAGE2LIGHT_LBFGS_TOLERANCE_GRAD = "1e-12"
$env:HNODECB_AFM04_STAGE2LIGHT_LBFGS_TOLERANCE_CHANGE = "1e-15"
$env:HNODECB_AFM04_STAGE2LIGHT_LBFGS_YS_THRESHOLD = "1e-15"
$env:HNODECB_AFM04_STAGE2LIGHT_PLATEAU_EARLY_STOP = "0"
$env:HNODECB_AFM04_STAGE2LIGHT_RECENT_VAL_EARLY_STOP = "0"

$driverLogHint = Join-Path $repoRoot "AFM04\stage2light\logs"

Write-Host "Running AFM04 stage2light with SHARDS=$Shards"
Write-Host "Repo root -> $repoRoot"
Write-Host "Python    -> $pythonExe"
Write-Host "Logs dir  -> $driverLogHint"
Write-Host "Hermetic env -> cleared $($staleStage2Env.Count) stale STAGE2LIGHT env vars"
Write-Host "Candidate -> prest2 candidate B 11 / source mech winner 78 / st1pl rank 247 / trial 43927; start state is original st1pl initial point"
Write-Host "GBO mode  -> soft mask ON, native Adam/AMSGrad $stage2AdamEpochs + LBFGS $stage2LbfgsEpochs, early stop OFF"
Write-Host "Adam guards -> step_controller OFF, step_guard OFF, epoch_retries OFF"

& $pythonExe -m AFM04.stage2light.main --driver
$exitCode = $LASTEXITCODE

if ($exitCode -ne 0) {
  throw "AFM04 stage2light local run failed with exit code $exitCode. See logs under $driverLogHint"
}
