param(
  [int]$Shards = 1,
  [switch]$AutoGenerateDataset
)

$ErrorActionPreference = "Stop"

$repoRoot = $PSScriptRoot
while ($true) {
  $hasAFM04 = Test-Path -Path (Join-Path $repoRoot "AFM04")
  if ($hasAFM04) {
    break
  }

  $parent = Split-Path -Path $repoRoot -Parent
  if ([string]::IsNullOrEmpty($parent) -or $parent -eq $repoRoot) {
    throw "Could not locate repository root from $PSScriptRoot"
  }
  $repoRoot = $parent
}

Set-Location -Path $repoRoot

$env:HNODECB_AFM04_STAGE2LIGHT_SHARD_COUNT = "$Shards"
$env:HNODECB_AFM04_STAGE2LIGHT_AUTOGEN_DATASET = if ($AutoGenerateDataset.IsPresent) { "1" } else { "0" }
$env:HNODECB_AFM04_STAGE2LIGHT_INPUT_RANK = "105"

$driverLogHint = Join-Path $repoRoot "AFM04\stage2light\logs"

Write-Host "Running AFM04 stage2light with SHARDS=$Shards"
Write-Host "Repo root -> $repoRoot"
Write-Host "Logs dir  -> $driverLogHint"

python -m AFM04.stage2light.main --driver
$exitCode = $LASTEXITCODE

if ($exitCode -ne 0) {
  throw "AFM04 stage2light local run failed with exit code $exitCode. See logs under $driverLogHint"
}
