param(
  [switch]$AutoGenerateDataset,
  [switch]$DisableAdaptiveGrid,
  [int]$WindowIndex = 1,
  [int]$Trials = 0,
  [int]$ShardCount = 8,
  [string]$Width = ""
)

$ErrorActionPreference = "Stop"

$repoRoot = $PSScriptRoot
while ($true) {
  $hasAFM04 = Test-Path -Path (Join-Path $repoRoot "AFM04")
  if ($hasAFM04) {
    break
  }

  $parent = Split-Path -Path $repoRoot -Parent
  if ([string]::IsNullOrEmpty($parent) -or $parent -eq $repoRoot) {
    throw "Could not locate repository root from $PSScriptRoot"
  }
  $repoRoot = $parent
}

Set-Location -Path $repoRoot

$pythonExe = Join-Path $repoRoot ".venv\Scripts\python.exe"
if (-not (Test-Path -Path $pythonExe)) {
  $pythonExe = "python"
}

if ($AutoGenerateDataset.IsPresent) {
  $env:HNODECB_AFM04_KFT_QCS_AUTOGEN_DATASET = "1"
}
if ($Trials -gt 0) {
  $env:HNODECB_AFM04_KFT_QCS_RANDOM_SEARCH_TRIALS = "$Trials"
}
if (-not [string]::IsNullOrWhiteSpace($Width)) {
  $env:HNODECB_AFM04_KFT_QCS_WIDTH = "$Width"
}

$env:HNODECB_AFM04_KFT_QCS_TRAIN_WINDOW_INDEX = "$WindowIndex"
$env:HNODECB_AFM04_KFT_QCS_WINDOW_MODE = "w0"
$env:HNODECB_AFM04_KFT_QCS_WINDOW_US = "6.288e-6"
$env:HNODECB_AFM04_KFT_QCS_RANDOM_SEARCH_SHARD_COUNT = "$ShardCount"
$env:HNODECB_AFM04_KFT_QCS_ADAPTIVE_GRID = if ($DisableAdaptiveGrid.IsPresent) { "0" } else { "1" }
$env:HNODECB_AFM04_KFT_QCS_ODE_RTOL = "1.0e-10"
$env:HNODECB_AFM04_KFT_QCS_ODE_ATOL = "1.0e-12"
$env:HNODECB_AFM04_KFT_QCS_RANDOM_SEARCH_USE_VAL = "0"

Write-Host "Running AFM04 KFT QCS random search only"
Write-Host "Repo root  -> $repoRoot"
Write-Host "Python    -> $pythonExe"
Write-Host "Output dir -> AFM04\\KAN_full_test\\quick_check_supervised"
Write-Host "Window     -> W0 index $WindowIndex"
Write-Host "RS shards  -> $ShardCount"
Write-Host "AGU        -> $(if ($DisableAdaptiveGrid.IsPresent) { 'OFF' } else { 'ON' })"
Write-Host "ODE tol    -> rtol=1e-10 atol=1e-12"
if ($Trials -gt 0) {
  Write-Host "Trials     -> $Trials"
}
if (-not [string]::IsNullOrWhiteSpace($Width)) {
  Write-Host "Width      -> $Width"
}

& $pythonExe -m AFM04.KAN_full_test.quick_check_supervised.random_search
$exitCode = $LASTEXITCODE

if ($exitCode -ne 0) {
  throw "AFM04 KFT QCS random search failed with exit code $exitCode"
}
