param(
  [switch]$AutoGenerateDataset,
  [switch]$DisableAdaptiveGrid,
  [int]$WindowIndex = 1,
  [int]$Epochs = 0,
  [int]$Trials = 0,
  [int]$ShardCount = 8,
  [int]$WarmstartTrial = 0,
  [string]$Width = ""
)

$ErrorActionPreference = "Stop"

$repoRoot = $PSScriptRoot
while ($true) {
  $hasAFM04 = Test-Path -Path (Join-Path $repoRoot "AFM04")
  if ($hasAFM04) {
    break
  }

  $parent = Split-Path -Path $repoRoot -Parent
  if ([string]::IsNullOrEmpty($parent) -or $parent -eq $repoRoot) {
    throw "Could not locate repository root from $PSScriptRoot"
  }
  $repoRoot = $parent
}

Set-Location -Path $repoRoot

$pythonExe = Join-Path $repoRoot ".venv\Scripts\python.exe"
if (-not (Test-Path -Path $pythonExe)) {
  $pythonExe = "python"
}

if ($AutoGenerateDataset.IsPresent) {
  $env:HNODECB_AFM04_KFT_QCS_AUTOGEN_DATASET = "1"
}
if ($Epochs -gt 0) {
  $env:HNODECB_AFM04_KFT_QCS_EPOCHS = "$Epochs"
}
if ($Trials -gt 0) {
  $env:HNODECB_AFM04_KFT_QCS_RANDOM_SEARCH_TRIALS = "$Trials"
}
if (-not [string]::IsNullOrWhiteSpace($Width)) {
  $env:HNODECB_AFM04_KFT_QCS_WIDTH = "$Width"
}

$env:HNODECB_AFM04_KFT_QCS_TRAIN_WINDOW_INDEX = "$WindowIndex"
$env:HNODECB_AFM04_KFT_QCS_WINDOW_MODE = "w0"
$env:HNODECB_AFM04_KFT_QCS_WINDOW_US = "6.288e-6"
$env:HNODECB_AFM04_KFT_QCS_RANDOM_SEARCH_SHARD_COUNT = "$ShardCount"
$env:HNODECB_AFM04_KFT_QCS_ADAPTIVE_GRID = if ($DisableAdaptiveGrid.IsPresent) { "0" } else { "1" }
$env:HNODECB_AFM04_KFT_QCS_LR_ADAPT = "1"
$env:HNODECB_AFM04_KFT_QCS_ODE_RTOL = "1.0e-10"
$env:HNODECB_AFM04_KFT_QCS_ODE_ATOL = "1.0e-12"
$env:HNODECB_AFM04_KFT_QCS_STEP_GUARD = "1"
$env:HNODECB_AFM04_KFT_QCS_RECENT_VAL_EARLY_STOP = "1"
$env:HNODECB_AFM04_KFT_QCS_WARMSTART_FROM_RANDOM_SEARCH = "1"
$env:HNODECB_AFM04_KFT_QCS_WARMSTART_FALLBACK_RANDOM = "0"
if ($WarmstartTrial -gt 0) {
  $env:HNODECB_AFM04_KFT_QCS_WARMSTART_TRIAL = "$WarmstartTrial"
} else {
  Remove-Item Env:\HNODECB_AFM04_KFT_QCS_WARMSTART_TRIAL -ErrorAction SilentlyContinue
}

Write-Host "Running AFM04 KFT quick check supervised pipeline"
Write-Host "Repo root  -> $repoRoot"
Write-Host "Python    -> $pythonExe"
Write-Host "Output dir -> AFM04\\KAN_full_test\\quick_check_supervised"
Write-Host "Mode       -> QCS-RS then QCS-GBO"
Write-Host "Window     -> W0 index $WindowIndex"
Write-Host "RS shards  -> $ShardCount"
Write-Host "Loss       -> formal rollout loss + Fts supervised loss; no lambda"
Write-Host "Step guard -> ON"
Write-Host "Early stop -> ON"
Write-Host "LR adapt   -> ON"
Write-Host "AGU        -> $(if ($DisableAdaptiveGrid.IsPresent) { 'OFF' } else { 'ON' })"
Write-Host "ODE tol    -> rtol=1e-10 atol=1e-12"
if ($Epochs -gt 0) {
  Write-Host "Epochs     -> $Epochs"
}
if ($Trials -gt 0) {
  Write-Host "RS trials  -> $Trials"
}
if ($WarmstartTrial -gt 0) {
  Write-Host "Warmstart  -> QCS RS trial $WarmstartTrial"
} else {
  Write-Host "Warmstart  -> QCS RS best"
}
if (-not [string]::IsNullOrWhiteSpace($Width)) {
  Write-Host "Width      -> $Width"
}

& $pythonExe -m AFM04.KAN_full_test.quick_check_supervised.random_search
$rsExitCode = $LASTEXITCODE

if ($rsExitCode -ne 0) {
  throw "AFM04 KFT quick check supervised random search failed with exit code $rsExitCode"
}

& $pythonExe -m AFM04.KAN_full_test.quick_check_supervised.main
$exitCode = $LASTEXITCODE

if ($exitCode -ne 0) {
  throw "AFM04 KFT quick check supervised failed with exit code $exitCode"
}
