param(
  [int]$Shards = 8,
  [switch]$AutoGenerateDataset
)

$ErrorActionPreference = "Stop"

$repoRoot = $PSScriptRoot
while ($true) {
  $hasAFM04 = Test-Path -Path (Join-Path $repoRoot "AFM04")
  if ($hasAFM04) {
    break
  }

  $parent = Split-Path -Path $repoRoot -Parent
  if ([string]::IsNullOrEmpty($parent) -or $parent -eq $repoRoot) {
    throw "Could not locate repository root from $PSScriptRoot"
  }
  $repoRoot = $parent
}

Set-Location -Path $repoRoot

$pythonExe = Join-Path $repoRoot ".venv\Scripts\python.exe"
if (-not (Test-Path -Path $pythonExe)) {
  $pythonExe = "python"
}

$schedulePath = Join-Path $repoRoot "AFM04\stage2light\stage2light_schedule.json"
$schedule = Get-Content -LiteralPath $schedulePath -Raw | ConvertFrom-Json
$stage2Epochs = [int]$schedule.epochs
$stage2AdamEpochs = [int]$schedule.adam_epochs
$stage2LbfgsEpochs = [int]$schedule.lbfgs_epochs
if ($stage2AdamEpochs -gt $stage2Epochs) {
  $stage2AdamEpochs = $stage2Epochs
}
if (($stage2AdamEpochs + $stage2LbfgsEpochs) -ne $stage2Epochs) {
  $stage2LbfgsEpochs = [Math]::Max(0, $stage2Epochs - $stage2AdamEpochs)
}

$stage1InputPath = Join-Path $repoRoot "AFM04\stage1pluslight\results_afm\afm_param_stage1pluslight_04.pkl"

$env:HNODECB_AFM04_PREST2_INPUT_PATH = $stage1InputPath
$env:HNODECB_AFM04_PREST2_SHARD_COUNT = "$Shards"
$env:HNODECB_AFM04_PREST2_LAYER_A_TOP_CANDIDATES = "100"
$env:HNODECB_AFM04_PREST2_LAYER_A_EPOCHS = "10"
$env:HNODECB_AFM04_PREST2_LAYER_B_TOP_CANDIDATES = "20"
$env:HNODECB_AFM04_PREST2_LAYER_B_EPOCHS = "20"
$env:HNODECB_AFM04_PREST2_CHECKPOINT_EVERY = "5"
$env:HNODECB_AFM04_PREST2_AUTOGEN_DATASET = if ($AutoGenerateDataset.IsPresent) { "1" } else { "0" }
$env:HNODECB_AFM04_PREST2_CANDIDATE_METRIC = "final_train_loss"
$env:HNODECB_AFM04_PREST2_STAGE2_ADAM_EPOCHS = "$stage2AdamEpochs"

$driverLogHint = Join-Path $repoRoot "AFM04\prestage2\logs"

Write-Host "Running AFM04 prestage2 with SHARDS=$Shards"
Write-Host "Layer A -> 100 mech winners, each with its best NN seed, 10 epochs"
Write-Host "Layer B -> top 20 top mech winners A, seamless resume to epoch 30"
Write-Host "Main schedule -> st2l total=$stage2Epochs, Adam prefix=$stage2AdamEpochs, LBFGS suffix=$stage2LbfgsEpochs"
Write-Host "Prest2 rule -> layers choose candidate set and prefix length only; optimizer phases are copied from st2l epoch numbers"
Write-Host "Metric  -> final_train_loss"
Write-Host "Stage1 input -> $stage1InputPath"
Write-Host "Repo root -> $repoRoot"
Write-Host "Python    -> $pythonExe"
Write-Host "Logs dir  -> $driverLogHint"

& $pythonExe -m AFM04.prestage2.main --driver
$exitCode = $LASTEXITCODE

if ($exitCode -ne 0) {
  throw "AFM04 prestage2 local run failed with exit code $exitCode. See logs under $driverLogHint"
}
