param(
  [int]$Shards = 8,
  [switch]$AutoGenerateDataset
)

$ErrorActionPreference = "Stop"

$repoRoot = $PSScriptRoot
while ($true) {
  $hasAFM04 = Test-Path -Path (Join-Path $repoRoot "AFM04")
  if ($hasAFM04) {
    break
  }

  $parent = Split-Path -Path $repoRoot -Parent
  if ([string]::IsNullOrEmpty($parent) -or $parent -eq $repoRoot) {
    throw "Could not locate repository root from $PSScriptRoot"
  }
  $repoRoot = $parent
}

Set-Location -Path $repoRoot

$env:HNODECB_AFM04_STAGE1_SHARD_COUNT = "$Shards"
$env:HNODECB_AFM04_STAGE1PLUS_WINDOW_MODE = "stage2_w1"
$env:HNODECB_AFM04_STAGE1PLUS_GRID_KS_NODES = "10"
$env:HNODECB_AFM04_STAGE1PLUS_GRID_CS_NODES = "10"
$env:HNODECB_AFM04_STAGE1PLUS_GRID_NN_SEEDS_PER_NODE = "1000"
$env:HNODECB_AFM04_KAN_TEST_RANDOM_SEARCH_USE_VAL = "0"
$env:HNODECB_AFM04_KAN_TEST_RANDOM_SEARCH_TRUE_RANDOM = "0"
$env:HNODECB_AFM04_KAN_TEST_RANDOM_SEARCH_FAIL_FAST = "1"
$env:HNODECB_AFM04_KAN_TEST_RANDOM_SEARCH_X1_GUARD_MULT = "1"
$env:HNODECB_AFM04_KAN_TEST_RANDOM_SEARCH_X2_GUARD_MULT = "1"

$autoGeneratePy = if ($AutoGenerateDataset.IsPresent) { "True" } else { "False" }
$driverLogHint = Join-Path $repoRoot "AFM04\stage1pluslight\logs"

Write-Host "Running AFM04 stage1pluslight with SHARDS=$Shards"
Write-Host "Repo root   -> $repoRoot"
Write-Host "Backend     -> KAN (KFT-RS style)"
Write-Host "Window mode -> $env:HNODECB_AFM04_STAGE1PLUS_WINDOW_MODE"
Write-Host "Search size -> $env:HNODECB_AFM04_STAGE1PLUS_GRID_KS_NODES x $env:HNODECB_AFM04_STAGE1PLUS_GRID_CS_NODES x $env:HNODECB_AFM04_STAGE1PLUS_GRID_NN_SEEDS_PER_NODE"
Write-Host "Trial split -> interleaved W1 trial sharding"
Write-Host "Bad trial   -> KFT-RS fail-fast guard ON"
Write-Host "Logs dir    -> $driverLogHint"

$py = @"
from AFM04.stage1pluslight.config import default_config
from AFM04.stage1pluslight.runner import launch_local_shards

cfg = default_config(r"$repoRoot")
launch_local_shards(cfg, shard_count=$Shards, auto_generate_dataset=$autoGeneratePy)
"@

$py | python -
$exitCode = $LASTEXITCODE

if ($exitCode -ne 0) {
  throw "AFM04 stage1pluslight local run failed with exit code $exitCode. See logs under $driverLogHint"
}
