param(
  [int]$Shards = 5,
  [switch]$AutoGenerateDataset
)

$ErrorActionPreference = "Stop"

$repoRoot = $PSScriptRoot
while ($true) {
  $hasAFM05 = Test-Path -Path (Join-Path $repoRoot "AFM05")
  if ($hasAFM05) {
    break
  }

  $parent = Split-Path -Path $repoRoot -Parent
  if ([string]::IsNullOrEmpty($parent) -or $parent -eq $repoRoot) {
    throw "Could not locate repository root from $PSScriptRoot"
  }
  $repoRoot = $parent
}

Set-Location -Path $repoRoot

$pythonExe = Join-Path $repoRoot ".venv\Scripts\python.exe"
if (-not (Test-Path -Path $pythonExe)) {
  $pythonExe = "python"
}

$staleStage1Env = @(
  Get-ChildItem Env:HNODECB_AFM05_STAGE1PLUS_* -ErrorAction SilentlyContinue
  Get-ChildItem Env:HNODECB_AFM05_STAGE1_* -ErrorAction SilentlyContinue
  Get-ChildItem Env:HNODECB_AFM05_KAN_TEST_* -ErrorAction SilentlyContinue
)
foreach ($item in $staleStage1Env) {
  Remove-Item -Path ("Env:\{0}" -f $item.Name) -ErrorAction SilentlyContinue
}

$env:HNODECB_AFM05_STAGE1_SHARD_COUNT = "$Shards"
$env:HNODECB_AFM05_STAGE1PLUS_WINDOW_MODE = "window_05_initial"
$env:HNODECB_AFM05_STAGE1PLUS_PIXEL_TAG = "184_152"
$env:HNODECB_AFM05_STAGE1PLUS_ARCH_WINDOW_US = "25.152e-6"
$env:HNODECB_AFM05_STAGE1PLUS_WINDOW_SAMPLE_STRIDE = "16"
$env:HNODECB_AFM05_STAGE1PLUS_GRID_KS_NODES = "10"
$env:HNODECB_AFM05_STAGE1PLUS_GRID_CS_NODES = "10"
$env:HNODECB_AFM05_STAGE1PLUS_GRID_NN_SEEDS_PER_NODE = "200"
$env:HNODECB_AFM05_STAGE1_RUN_SEED = "20260406"
$env:HNODECB_AFM05_STAGE1_FIXED_HIDDEN_NODES = "7"
$env:HNODECB_AFM05_KAN_TEST_WIDTH_HIDDEN = "7"
$env:HNODECB_AFM05_KAN_TEST_RANDOM_SEARCH_USE_VAL = "0"
$env:HNODECB_AFM05_KAN_TEST_RANDOM_SEARCH_FAIL_FAST = "1"
$env:HNODECB_AFM05_KAN_TEST_RANDOM_SEARCH_X1_GUARD_MULT = "1"
$env:HNODECB_AFM05_KAN_TEST_X1_ONLINE_ERROR_GUARD = "0"
$env:HNODECB_AFM05_KAN_TEST_X1_ONLINE_ERROR_GUARD_PCT = "0.05"
$env:HNODECB_AFM05_KAN_TEST_X1_ONLINE_ERROR_GUARD_TASK_PCTS = "5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95"

$autoGeneratePy = if ($AutoGenerateDataset.IsPresent) { "True" } else { "False" }
$driverLogHint = Join-Path $repoRoot "AFM05\stage1pluslight\logs"

Write-Host "Running AFM05 stage1pluslight with SHARDS=$Shards"
Write-Host "Repo root   -> $repoRoot"
Write-Host "Python      -> $pythonExe"
Write-Host "Hermetic env -> cleared $($staleStage1Env.Count) stale stage1/KAN vars"
Write-Host "Backend     -> KAN (stage1pluslight random search)"
Write-Host "KAN width   -> 3-$env:HNODECB_AFM05_KAN_TEST_WIDTH_HIDDEN-1"
Write-Host "Window mode -> $env:HNODECB_AFM05_STAGE1PLUS_WINDOW_MODE"
Write-Host "Pixel tag   -> $env:HNODECB_AFM05_STAGE1PLUS_PIXEL_TAG"
Write-Host "Window span -> $env:HNODECB_AFM05_STAGE1PLUS_ARCH_WINDOW_US s"
Write-Host "Sample      -> uniform stride=$env:HNODECB_AFM05_STAGE1PLUS_WINDOW_SAMPLE_STRIDE"
Write-Host "Search size -> $env:HNODECB_AFM05_STAGE1PLUS_GRID_KS_NODES x $env:HNODECB_AFM05_STAGE1PLUS_GRID_CS_NODES x $env:HNODECB_AFM05_STAGE1PLUS_GRID_NN_SEEDS_PER_NODE"
Write-Host "NN seeds    -> initseed = $env:HNODECB_AFM05_STAGE1_RUN_SEED + seedbank"
Write-Host "Guards      -> x1_amp_mult=$env:HNODECB_AFM05_KAN_TEST_RANDOM_SEARCH_X1_GUARD_MULT; x1_online_error_enabled=$env:HNODECB_AFM05_KAN_TEST_X1_ONLINE_ERROR_GUARD; x1_online_error=$env:HNODECB_AFM05_KAN_TEST_X1_ONLINE_ERROR_GUARD_PCT% at [$env:HNODECB_AFM05_KAN_TEST_X1_ONLINE_ERROR_GUARD_TASK_PCTS]%"
Write-Host "Truth side  -> disabled; AFM05 uses tagged experimental x1/x2/x2dot and global reconstructed F_actuation(t)"
Write-Host "Logs dir    -> $driverLogHint"

$py = @"
from AFM05.stage1pluslight.config import default_config
from AFM05.stage1pluslight.runner import launch_local_shards

cfg = default_config(r"$repoRoot")
launch_local_shards(cfg, shard_count=$Shards, auto_generate_dataset=$autoGeneratePy)
"@

$py | & $pythonExe -
$exitCode = $LASTEXITCODE

if ($exitCode -ne 0) {
  throw "AFM05 stage1pluslight local run failed with exit code $exitCode. See logs under $driverLogHint"
}
